[project]
name = "odoo-addons-oca-survey"
version = "17.0.20260723.0"
dependencies = [
    "odoo-addon-partner_survey>=17.0dev,<17.1dev",
    "odoo-addon-survey_answer_generation>=17.0dev,<17.1dev",
    "odoo-addon-survey_certification_py3o>=17.0dev,<17.1dev",
    "odoo-addon-survey_certification_sending>=17.0dev,<17.1dev",
    "odoo-addon-survey_contact_generation>=17.0dev,<17.1dev",
    "odoo-addon-survey_contact_generation_model_selection>=17.0dev,<17.1dev",
    "odoo-addon-survey_crm_generation>=17.0dev,<17.1dev",
    "odoo-addon-survey_crm_generation_model_selection>=17.0dev,<17.1dev",
    "odoo-addon-survey_crm_sale_generation>=17.0dev,<17.1dev",
    "odoo-addon-survey_legal>=17.0dev,<17.1dev",
    "odoo-addon-survey_multi_company>=17.0dev,<17.1dev",
    "odoo-addon-survey_next_survey_update_partner>=17.0dev,<17.1dev",
    "odoo-addon-survey_partner_representative>=17.0dev,<17.1dev",
    "odoo-addon-survey_question_type_binary>=17.0dev,<17.1dev",
    "odoo-addon-survey_question_type_model_selection>=17.0dev,<17.1dev",
    "odoo-addon-survey_resource_booking>=17.0dev,<17.1dev",
    "odoo-addon-survey_result_mail>=17.0dev,<17.1dev",
    "odoo-addon-survey_sale_generation>=17.0dev,<17.1dev",
    "odoo-addon-survey_skip_start>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
